#!/usr/bin/env bash
# Install and configure HAProxy on lb-01 server

# colors
blue='\e[1;34m'
brown='\e[0;33m'
green='\e[1;32m'
reset='\033[0m'

echo -e "${blue}Updating and doing some minor checks...${reset}\n"

function install() {
	command -v "$1" &> /dev/null

	# Check if the command exists
	if [ $? -ne 0 ]; then
		echo -e "	Installing: ${brown}$1${reset}\n"
		sudo apt-get update -y -qq && \
			sudo apt-get install -y "$1" -qq
		echo -e "\n"
	else
		echo -e "	${green}${1} is already installed.${reset}\n"
	fi
}

# Install HAProxy
install haproxy

echo -e "\n${blue}Setting up some minor stuff.${reset}\n"

# Backup default HAProxy configuration file
sudo cp /etc/haproxy/haproxy.cfg haproxy_default.backup

# Define the HAProxy server configuration
server_config="
defaults
  mode http
  timeout client 15s
  timeout connect 10s
  timeout server 15s
  timeout http-request 10s

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 207288-web-01 107.23.108.163:80 check
    server 207288-web-02 52.91.124.68:80 check
"

# Update HAProxy configuration file with the defined server configuration
echo "$server_config" | sudo dd status=none of=/etc/haproxy/haproxy.cfg

# Enable HAProxy to be started by init script
echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy

# Restart HAProxy service
sudo service haproxy restart

