#!/usr/bin/env bash

# This script gracefully reloads the Gunicorn service managed by systemd

# Reload the Gunicorn service managed by systemd
sudo systemctl reload gunicorn

if [ $? -eq 0 ]; then
  echo "Gunicorn gracefully reloaded"
else
  echo "Failed to reload Gunicorn"
fi

